### ISSUE TITLE
Controller Services are not getting committed while committing job-flow (associated with existing job) into NiFi Registry

### ISSUE THREAD

**Issue by sanjiv1980** [B23admin/nifi-stateless-operator#5]
I have written simple job which do the file listing from S3 , related to that , I have attached controller services (AWS Credentials Provider service) which generally contains AWS credentials stuff . I thought while committing Job into NiFi-Registry those services should also be a part of that , but It seems that is not the case . I am getting exception below  

```
kubectl logs nififn-sample-job-pfrn4 -n nifi-fn-operator-system
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/nifi-1.8.0/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" java.lang.IllegalArgumentException: context is not valid: 'AWS Credentials Provider service' validated against 'b7f1e9d1-9ba8-321c-8c7c-31dab0ef0161' is invalid because Property references a Controller Service that does not exist
'AWS Credentials Provider service' validated against 'b7f1e9d1-9ba8-321c-8c7c-31dab0ef0161' is invalid because Invalid Controller Service: b7f1e9d1-9ba8-321c-8c7c-31dab0ef0161 is not a valid Controller Service Identifier
	at org.apache.nifi.fn.core.FnProcessorWrapper.initialize(FnProcessorWrapper.java:125)
	at org.apache.nifi.fn.core.FnProcessorWrapper.runRecursive(FnProcessorWrapper.java:136)
	at org.apache.nifi.fn.core.FnFlow.runOnce(FnFlow.java:201)
	at org.apache.nifi.fn.runtimes.Program.main(Program.java:104)```

**Comment by dbkegley** [comment]
This looks like a bug with nifi-stateless. It would be great if you could create a JIRA issue on the Apache NiFi jira for this! 

https://issues.apache.org/jira/projects/NIFI/issues

**Comment by sanjiv1980** [comment]
Thank you, I will do that .

**Comment by sanjiv1980** [comment]
I created JIRA ticket : https://issues.apache.org/jira/browse/NIFI-6577

**Comment by dbkegley** [comment]
My mistake, I created my controller service in a nested PG.

Controller Services are initialized correctly if they are created on the same ProcessGroup that is committed to registry (eg. right click the PG -> configuration -> Controller Services -> +). Controller services created globally (from the hamburger menu) are not added to registry and cannot be initialized by nifi-stateless.

I have created https://issues.apache.org/jira/browse/NIFI-6579 to handle Controller Services which should be created recursively

**Comment by sanjiv1980** [comment]
Hi David,
I tried to keep everything on same process group , but still I am getting that error 

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/nifi-1.8.0/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" java.lang.IllegalArgumentException: context is not valid: 'AWS Credentials Provider service' validated against '1bf2e043-50c8-3166-ac84-d0f0d7b59ba0' is invalid because Controller Service with ID 1bf2e043-50c8-3166-ac84-d0f0d7b59ba0 is not enabled
'' is invalid because Controller service 1bf2e043-50c8-3166-ac84-d0f0d7b59ba0 for  is not enabled
	at org.apache.nifi.fn.core.FnProcessorWrapper.initialize(FnProcessorWrapper.java:125)
	at org.apache.nifi.fn.core.FnProcessorWrapper.runRecursive(FnProcessorWrapper.java:136)
	at org.apache.nifi.fn.core.FnFlow.runOnce(FnFlow.java:201)
	at org.apache.nifi.fn.runtimes.Program.main(Program.java:104)

```

I can attached fe screen shot 
<img width="1313" alt="Screen Shot 2019-08-26 at 2 03 41 PM" src="https://user-images.githubusercontent.com/2685528/63677423-92d26180-c80a-11e9-8aed-814d48551715.png">


<img width="1856" alt="Screen Shot 2019-08-26 at 2 03 24 PM" src="https://user-images.githubusercontent.com/2685528/63677457-a1207d80-c80a-11e9-9fbc-fa2128debbbf.png">

Could you please guide me If I am doing some mistake ...?

Note : When I ran from NiFi Dashboard , It gave me the result what I expected .

Regards,
sanjiv

**Comment by dbkegley** [comment]
Hm this looks like a new error. Before the error was `does not exist` but this time it says the service is `not enabled`

I think this could be related to some of the changes that were merged into nifi-stateless since the original container was published. I'll update the container that the operator uses and see if that helps

**Comment by sanjiv1980** [comment]
sure..!! Thanks , Please let me know , once you done.!!!So that I can start testing ...

**Comment by sanjiv1980** [comment]
@dbkegley Is there any update .? Have you revert back your changes .?

**Comment by sanjiv1980** [comment]
Hi @dbkegley , have you updated the operator code to accomodate nifi-stateless changes .?

Thanks
sanjiv

**Comment by dbkegley** [comment]
Yes I have, you can install the new operator with:

`kubectl apply -f https://raw.githubusercontent.com/b23llc/nifi-stateless-operator/master/config/deploy/nifi-stateless-operator.yaml`

The main readme is up to date with the current changes. The only thing to note is that the `runFrom: xml` functionality will likely be removed as soon as I have time. There is some ongoing discussion about the best way to initialize a NiFi flow from a file

https://mail-archives.apache.org/mod_mbox/nifi-dev/201909.mbox/%3C9D013BE6-36B9-4078-830E-23BAF5F96E09%40apache.org%3E
