### ISSUE TITLE
Is there any way to update NiFi version 

### ISSUE THREAD

**Issue by sanjiv1980** [B23admin/nifi-stateless-operator#6]
While working with NiFi-Fn-Operator , I got to know like it has built on NiFi 1.8.0 (currently it's 1.9.X) version , Is there any way that I can update the base version from 1.8.0 to 1.9.x.? 

Note : I saw there is YAML file inside nifi-docker directory which pulls the images 1.8.0 . Can I go ahead and update that file to update the version , that make sense..?
```
FROM apache/nifi:1.8.0
USER root
ADD start.sh ${NIFI_BASE_DIR}/scripts/start.sh
RUN chown nifi:nifi ${NIFI_BASE_DIR}/scripts/start.sh
USER nifi

**Comment by dbkegley** [comment]
I've been using the nifi-docker directory as a convenience for [deploying a nifi instance](https://github.com/b23llc/nifi-fn-operator/blob/master/config/nifi/nifi.yaml#L22) to use as a canvas for designing flows which will run on nifi-stateless.   The 1.8.0 image is not actually used by the operator itself though. The operator is using [this docker image](https://hub.docker.com/r/samhjelmfelt/nifi-fn/tags) currently, but will be updated to use [this one](https://hub.docker.com/r/apache/nifi-stateless/tags) once nifi-1.10.0 is officially released.  Either way, feel free to update the version if you want to use the latest release, that should be fine
